headers = {
    'authority': 'mbasic.facebook.com',
     	  "method": 'GET',
 		   "scheme": 'https',
 		    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  		   'accept-language': 'en-ZA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7',
  		   'cache-control': 'max-age=0',
  		   'sec-ch-ua': '"(Not(A:Brand";v="99"',
  		   'sec-ch-ua-mobile': '?1',
    		 'sec-ch-ua-platform': '"iOS"',
 		    'sec-fetch-dest': 'document',
 		    'sec-fetch-mode': 'navigate',
    		 'sec-fetch-site': 'none',
 		    'sec-fetch-user': '?1',
 		    'upgrade-insecure-requests': '1',
  		   'user-agent': pro}


'authority': 'p.facebook.com',
			"method": 'GET',
 		   "scheme": 'https',
  		  'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    		'accept-language': 'en-ZA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7',
  		  'cache-control': 'max-age=0',
    		'sec-ch-ua': '"Chromium";v="107", "Not=A?Brand";v="24"',
   		 'sec-ch-ua-mobile': '?1',
  		  'sec-ch-ua-platform': '"Android"',
    		'sec-fetch-dest': 'document',
  		  'sec-fetch-mode': 'navigate',
   		 'sec-fetch-site': 'none',
  		  'sec-fetch-user': '?1',
   		 'upgrade-insecure-requests': '1',
   		 'user-agent': pro}
   
   
   headers = {
    'authority': 'mbasic.facebook.com',
   	   "method": 'GET',
 	     "scheme": 'https',
 	      'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
	       'accept-language': 'en-ZA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7',
   	    'cache-control': 'max-age=0',
 	      'sec-ch-ua': '"Chromium";v="107", "Not=A?Brand";v="24"',
 		  'sec-ch-ua-mobile': '?0',
 		  'sec-ch-ua-platform': '"Linux"',
  	    'sec-fetch-dest': 'document',
   	   'sec-fetch-mode': 'navigate',
	      'sec-fetch-site': 'none',
	      'sec-fetch-user': '?1',
   	   'upgrade-insecure-requests': '1',
          'user-agent': pro,}
